using System;
using System.Collections.Generic;
using System.Globalization;
using idev.LoggerWrapper;
using NUnit.Framework;
using LogLevel = idev.LoggerWrapper.LogLevel;

namespace idevUnitTests.Log
{
    /// <summary>
    /// Regression tests for the trace level check and for the prefix generated by LoggerWrapper(ILogMethods, string).
    /// </summary>
    [TestFixture]
    public class LoggerWrapperTraceAndPrefixTests
    {
        private const string TimestampFormat = "yyyy-MM-dd HH:mm:ss.fff";

        private static LogMethods CreateRecordingLogMethods(ICollection<string> messages, bool isEnabled)
        {
            return new LogMethods(
                x => messages.Add(x),
                x => messages.Add(x.Message),
                (x, y) => messages.Add(x + y.Message),
                isEnabled);
        }

        private static LoggerWrapper CreateLogger(LogMethods traceLog, LogMethods debugLog)
        {
            return new LoggerWrapper(null, null, null, traceLog, debugLog, null);
        }

        #region Trace level tests

        [Test]
        public void Logger_TraceDisabledDebugEnabled_TraceIsNotWritten()
        {
            //Arrange
            var traceMessages = new List<string>();
            var debugMessages = new List<string>();
            var logger = CreateLogger(
                CreateRecordingLogMethods(traceMessages, false),
                CreateRecordingLogMethods(debugMessages, true));
            var exposedMessages = new List<Tuple<LogLevel, string, Exception>>();
            logger.LogMessageHandler += (x, y, z) => exposedMessages.Add(new Tuple<LogLevel, string, Exception>(x, y, z));

            //Act
            logger.Trace("message");
            logger.Trace(new Exception("exception"));
            logger.Trace("message", new Exception("exception"));

            //Assert
            Assert.IsFalse(logger.IsTraceEnabled, "Trace should be reported as disabled.");
            Assert.IsTrue(logger.IsDebugEnabled, "Debug should be reported as enabled.");
            Assert.AreEqual(0, traceMessages.Count, "Trace overloads must not write while trace is disabled.");
            Assert.AreEqual(0, exposedMessages.Count, "Trace overloads must not expose messages while trace is disabled.");
        }

        [Test]
        public void Logger_TraceEnabledDebugDisabled_TraceIsWritten()
        {
            //Arrange
            var traceMessages = new List<string>();
            var debugMessages = new List<string>();
            var logger = CreateLogger(
                CreateRecordingLogMethods(traceMessages, true),
                CreateRecordingLogMethods(debugMessages, false));
            var exposedMessages = new List<Tuple<LogLevel, string, Exception>>();
            logger.LogMessageHandler += (x, y, z) => exposedMessages.Add(new Tuple<LogLevel, string, Exception>(x, y, z));

            //Act
            logger.Trace("message");
            logger.Trace(new Exception("exception"));
            logger.Trace("message", new Exception("exception"));

            //Assert
            Assert.IsTrue(logger.IsTraceEnabled, "Trace should be reported as enabled.");
            Assert.IsFalse(logger.IsDebugEnabled, "Debug should be reported as disabled.");
            Assert.AreEqual(3, traceMessages.Count, "All trace overloads must write while trace is enabled.");
            Assert.AreEqual(3, exposedMessages.Count, "All trace overloads must expose messages while trace is enabled.");
        }

        [Test]
        public void Logger_TraceEnabledDebugDisabled_DebugIsNotWritten()
        {
            //Arrange
            var traceMessages = new List<string>();
            var debugMessages = new List<string>();
            var logger = CreateLogger(
                CreateRecordingLogMethods(traceMessages, true),
                CreateRecordingLogMethods(debugMessages, false));

            //Act
            logger.Debug("message");
            logger.Debug(new Exception("exception"));
            logger.Debug("message", new Exception("exception"));

            //Assert
            Assert.AreEqual(0, debugMessages.Count, "Debug overloads must not write while debug is disabled.");
        }

        #endregion

        #region Prefix tests

        [Test]
        public void Logger_CreateWithName_PrefixSeparatesLevelFromMessage()
        {
            //Arrange
            var messages = new List<string>();
            var logger = new LoggerWrapper(CreateRecordingLogMethods(messages, true), "TestName");

            //Act
            logger.Info("Message");

            //Assert
            Assert.AreEqual(1, messages.Count);
            StringAssert.EndsWith("TestName Info: Message", messages[0]);
        }

        [Test]
        public void Logger_CreateWithName_PrefixUsesCurrentTimeInInvariantFormat()
        {
            //Arrange
            var messages = new List<string>();
            var logger = new LoggerWrapper(CreateRecordingLogMethods(messages, true), "TestName");
            var before = DateTime.Now;

            //Act
            logger.Info("Message");

            //Assert
            Assert.AreEqual(1, messages.Count);
            var timestampText = messages[0].Substring(0, TimestampFormat.Length);
            DateTime timestamp;
            Assert.IsTrue(
                DateTime.TryParseExact(timestampText, TimestampFormat, CultureInfo.InvariantCulture, DateTimeStyles.None, out timestamp),
                "Prefix must start with an invariant '" + TimestampFormat + "' timestamp but was '" + timestampText + "'.");
            Assert.GreaterOrEqual(timestamp, before.AddSeconds(-5), "Prefix timestamp must be the time of the event, not the start of the day.");
            Assert.LessOrEqual(timestamp, DateTime.Now.AddSeconds(5), "Prefix timestamp must be the time of the event.");
        }

        #endregion
    }
}
